### ISSUE TITLE
-Q "->users" invalid option?

### ISSUE THREAD

**Issue by JesseLeite** [ggreer/the_silver_searcher#1222]
Not sure if this is bug, or if I'm misunderstanding something?

```
ag -Q "->users"
```

That crashes ag with:

```
ag: invalid option -- >
```

**Comment by aswild** [comment]
The `->users` argument is getting parsed as an option because it begins with a `-`, this is just how [getopt_long(3)](https://linux.die.net/man/3/getopt_long) works and is common is the majority of *nix programs.

To search for a pattern beginning with a `-`, add a `--` between the options and the pattern/search paths

```
ag -Q -- "->users"
```

**Comment by JesseLeite** [comment]
@aswild Oh interesting, thank you!  Closing this issue.

By the way, will `--` work on Windows as well?  Or can I only do this in *nix environments?

**Comment by aswild** [comment]
I'd guess yes, but I'm not sure off the top of my head, depends on the getopt implementation.  Just try it and find out!
