### ISSUE TITLE
Ubuntu package

### ISSUE THREAD

**Issue by rking** [ggreer/the_silver_searcher#183]
I just found out that `apt-get install the_silver_searcher` works not.

Who is the best person to start fixing this?

**Comment by chenyangguang** [comment]
➜  ~ sudo apt-get install  silversearcher-ag
Reading package lists... Done
Building dependency tree       
Reading state information... Done
silversearcher-ag is already the newest version (0.31.0-2).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up redis-server (2:3.0.6-1) ...
Job for redis-server.service failed because the control process exited with error code. See "systemctl status redis-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript redis-server, action "start" failed.
dpkg: error processing package redis-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 redis-server
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by richarson** [comment]
@chenyangguang this is not a problem with ag:

"➜ ~ sudo apt-get install silversearcher-ag
Reading package lists... Done
Building dependency tree

Reading state information... Done
**silversearcher-ag is already the newest version** (0.31.0-2).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
**Setting up redis-server** (2:3.0.6-1) ...
Job for redis-server.service failed because the control process exited with error code. See "systemctl status redis-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript redis-server, action "start" failed.
**dpkg: error processing package redis-server** (--configure):
subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
redis-server
E: Sub-process /usr/bin/dpkg returned an error code (1)"
