### ISSUE TITLE
Help installing ag on a machine without sudo access

### ISSUE THREAD

**Issue by kaushalmodi** [ggreer/the_silver_searcher#341]
Hi,

I checked that my machine has pkg-config, automake and lzma ( I am not sure if that is different from liblzma-dev). It doesn't have PCRE.

I built PCRE from http://www.pcre.org/ but that did not work. I kept on getting the below error when running ./build.sh for ag

./configure: line 3930: syntax error near unexpected token `PCRE,'
./configure: line 3930: `PKG_CHECK_MODULES(PCRE, libpcre)'

I used the following command for configure:
`./configure --prefix=$HOME/usr_local CPPFLAGS="-I$HOME/usr_local/include" LDFLAGS="-static -L$HOME/usr_local/include  -L$HOME/usr_local/lib"`
because I install PCRE to my local folder $HOME/usr_local and I plan to install ag to the same.

When I acked for libpcre in $HOME/usr_local, it was actually there and still it failed the configure step.

As I don't have admin rights, I can't use yum or apt-get.

Any help will be appreciated, thanks.

**Comment by michaelmior** [comment]
Just a note that this error is caused by missing `pkg-config`. It seems to be already noted in the README that this is required.

**Comment by DonghuaLau** [comment]
I have installed pkg-config, but still has this error, on CentOS 6.4. Anyone has idea?

**Comment by ernstki** [comment]
Simply having `pkg-config` available is not sufficient on CentOS 6.4. Modifying `$PKG_CONFIG_PATH` and even putting a newer version of `pkg-config` in the path _ahead_ of the OS-installed one didn't seem to work for me either. The only way I found to get it working was to make the manual changes to `configure` and `Makefile` as @DonghuaLau suggests.

**Comment by NickWer** [comment]
Just wanted to add a note here, since I was having issues with this as well and this showed up frequently in the top results on google: The latest versions of  PCRE is actually PCRE-2, which is incompatible with ag. Instead, you'll need to download and install v8.44, which is the last release (as of right now) for the original PCRE. Once I'd done that, I was able to build without much of an issue using the latest  pkg-config, automake, and xz
