### ISSUE TITLE
Print match only

### ISSUE THREAD

**Issue by zachlatta** [ggreer/the_silver_searcher#400]
Is it possible to only print the match?

Say I have the following file:

```
Lorem Ipsum is simply dummy text of the printing and typesetting industry.
```

If I run `ag "L.*m"` is there a way to have it only print `Lorem` and not the entire line?

**Comment by eevee** [comment]
Closable now?

**Comment by padde** [comment]
First of all, thanks for your work @gurgeous!

However, I am still having some issues with the new option. All examples assume we have a file `foo.txt` with the following contents in the current directory:

```
foo foobar
bar
baz
foobar
quux
```

(a) It would be good to add the `-o` option to the man page. Potentially there are more options missing, but I don’t have the time to check right now.

(b) One big issue for me is when multiple matches occur on the same line. Consider the output of the pattern `'f\w+'` with my workaround presented above:

```
~$ ag --color 'f\w+' | ruby -ne 'puts $_.scan(/\x1b\[30;43m(.*?)\x1b/)'
foo
foobar
foobar
```

However, using the `-o` option this yields

```
~$ ag -o 'f\w+'
foo.txt
1:foofoobar
4:foobar
```

Notice how the matches are joined together. This makes it impossible to use this for proper scripting. I think this calls for another option `--multi-match` that works a bit like `--vimgrep`. It would enable printing multiple matches on multiple lines and also enable the `--column` option by default. This would make it re-usable as part of `--vimgrep`. The `--column` option should be enabled by `--multi-match`. The `--multi-match` option should then be automatically enabled when using `-o`. Some test cases follow:

The `--multi-match` option should enable `--column` automatically:

```
~$ ag --multi-match 'f\w+'
foo.txt
1:1:foo foobar
1:5:foo foobar
4:1:foobar
```

The `--multi-match` option should work with `--color` (colored output highlighted with `[...]`):

```
~$ ag --multi-match 'f\w+'
foo.txt
1:1:[foo] foobar
1:5:foo [foobar]
4:1:foobar
```

The `-o` option should enable `--multi-match` automatically:

```
~$ ag -o 'f\w+'
foo.txt
1:1:foo
1:5:foobar
4:1:foobar
```

The `--vimgrep` option should be equivalent to `--multi-match --nogroup`. Probably we could replace the current `--vimgrep` implementation by simply setting `--multi-match --nogroup`:

```
~$ ag --vimgrep 'f\w+'
foo.txt:1:1:foo foobar
foo.txt:1:5:foo foobar
foo.txt:4:1:foobar

~$ ag --multi-match --nogroup 'f\w+'
foo.txt:1:1:foo foobar
foo.txt:1:5:foo foobar
foo.txt:4:1:foobar
```

(c) As I plan on using this for scripting, I need to extract the matches, and the matches only from the output. I know I can use `--nogroup` and then pipe the output through `cut` in order to extract the matches:

> Note that in the examples below, I assume the _currently not implemented_ `--multi-match` behaviour that I described above, including the implied output of the column number.

```
~$ ag --nogroup -o 'f\w+' | cut -d: -f4
foo
foobar
foobar
```

Still, I think it would be much prettier and less fragile if we could configure all parts of the output. Some parts are already there, for example the `--no-numbers` option, so only the file name and the column number would remain:

```
~$ ag --nogroup --no-numbers -o 'f\w+' 
foo.txt:1:foo
foo.txt:5:foobar
foo.txt:1:foobar
```

therefore, we would also need `--nocolumn` and `--nofilename` options:

```
~$ ag --nogroup --nocolumn --no-numbers -o 'f\w+' 
foo.txt:foo
foo.txt:foobar
foo.txt:foobar

~$ ag --nogroup --nocolumn --nofile --no-numbers -o 'f\w+' 
foo
foobar
foobar
```

maybe we could even have a `--nolocation` option that omits this kind of output completely:

```
~$ ag --nogroup --nolocation -o 'f\w+' 
foofoobar
foobar
```

(e) As I think of it, the `--line-numbers` and `--no-numbers` option are named inconsistently. Shouldn't they be called `--[no]numbers`, just like `--[no]heading`, `--[no]break` and `--[no]group`? I'd keep the oddly named cousins around but print a deprecation warning to stderr, then eventually remove them in the future.

Let me know what you guys think of all this. Of course we probably need to extract some separate issues here, but I thought it would be smarter to discuss the concept first.

**Comment by padde** [comment]
Side note: Ack has the `--nocolumn` as well as the `-H, --with-filename` and the `-h, --no-filename` options. So folks looking for a solution for scripting: `ack -ho PATTERN` will do the trick. Some examples for comparison:

```
~$ ack -o 'f\w+'
foo
foobar
foobar

~$ ack -o --with-filename 'f\w+'
foo.txt
1:foo
1:foobar
4:foobar
```

**Comment by gurgeous** [comment]
A few comments:

Yes, this should be in the man page. Oops. Want to submit a pull request? I think maybe you just have to edit ag.1.md.

The current implementation is very simple and just spits out matches and newlines. It would probably be better to move to something more like grep's approach, where each match gets a new line. That decision is up to @ggreer, though.

```sh
$ grep foo foo.txt
foo foobar
foobar

$ grep -o foo foo.txt
foo
foo
foo

# note line numbers
$ grep -on foo foo.txt
1:foo
foo
4:foo
```

Don't be surprised if this languishes until some enterprising person submits a pull request. Incremental pull requests with tests and comments are always appreciated! :)

Separately, it would be nice to review the output flags and make a few adjustments. Probably not in the context of this issue, though.

**Comment by ggreer** [comment]
Alright, I've cleaned up the output of `--only-matching` in master. By default, it now behaves like `grep` and `ack`. `ag -o file_to_seach.txt` prints out matches on their own lines, and nothing else. If you don't specify the file to search, `ag` will print out file names and line numbers just like normal, though each match will still be on its own line. Except for the highlight colors, this output is identical to `ack`.

**Comment by padde** [comment]
@ggreer thanks this looks like a good default. However it would be useful to have this work properly with `--column`. Currently, the output is

```
~$ ag -o --column 'f\w+'
foo.txt
1:1:foo
1:foobar
4:1:foobar
```

Notice that the column number is missing in the second line, i.e. the second match in the first line. The output should be

```
~$ ag -o --column 'f\w+'
foo.txt
1:1:foo
1:5:foobar
4:1:foobar
```

**Comment by ggreer** [comment]
Good catch. I added a test case and fixed it in master.

**Comment by padde** [comment]
Great so I could improve my original snippet from this scary monster

```
ag --color PATTERN | ruby -ne 'puts $_.scan(/\x1b\[30;43m(.*?)\x1b/)'
```

to this

```
ag -o --nogroup PATTERN | cut -d: -f3
```

Much better. Thanks for your effort. I will submit a PR containing the missing documentation (man page). The formatting options I suggested are a different issue. I think this ticket can be closed now.

**Comment by zachlatta** [comment]
Awesome! Glad this was added :thumbs up:. I'll leave it to @ggreer to close the issue when all is done with the man page update.

**Comment by padde** [comment]
@zachlatta the man page was already updated, I just forgot to mention this ticket in my PR.

**Comment by zachlatta** [comment]
Ah, gotcha. So this is ready for closing then?

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by padde** [comment]
If you're happy with it – go ahead!

Cheers

**Comment by ggreer** [comment]
Nice work, everyone. :)

**Comment by markstos** [comment]
What come people really want is print only a *capture*, not the whole match. This is already possible through the PCRE library, but it could be hard to realize how to do this with a deep dive into the documentation. A short example added to the `ag` documentation could help.  For example, let's say you have a bunch of  HTML anchor tags that link to `https://` domains you want to pull out the domain names. This works:

      ag -o 'https://\K.*?(?=")'

The key things to know about PCREs here are:

 1. `\K` is used to reset the match start, so text before it won't be returned in the match.
 2.  `(?=)` is the Lookahead Assesrtion construct. It *looks ahead* to see if the remaining text would appear, without including the text as part of the match. 

By combining these two PCRE features, you can remove both preceding and following text from the match.
