### ISSUE TITLE
Bus error: 10 running on Mac OS 10.10.1 

### ISSUE THREAD

**Issue by jawshooah** [ggreer/the_silver_searcher#588]
I was doing a stress-test, recursively searching everything in my home directory for a simple string, when this happened:
```bash
$ ag "alias git" --debug
... a TON of debugging output ...
DEBUG: pattern *.sublime-workspace doesn't match file ubiquitous_AllSignatures.plist
DEBUG: pattern *.swp doesn't match file ubiquitous_AllSignatures.plist
DEBUG: pattern *.tar doesn't match file ubiquitous_AllSignatures.plist
DEBUG: pattern *.zip doesn't match file ubiquitous_AllSignatures.plist
DEBUG: pattern .DS_Store? doesn't match file ubiquitous_AllSignatures.plist
DEBUG: pattern ._* doesn't match file ubiquitous_AllSignatures.plist
DEBUG: file ubiquitous_AllSignatures.plist not ignored
DEBUG: ./Library/Mobile Documents.850126691/com~apple~mail/Data/MailData/Signatures/ubiquitous_2B8C5EDF-1C83-471B-B3BC-27582AACB224.mailsignature added to work queue
DEBUG: ./Library/Mobile Documents.850126691/com~apple~mail/Data/MailData/Signatures/ubiquitous_AllSignatures.plist added to work queue
DEBUG: ./Library/Mobile Documents.850126691/com~apple~mail/Data/MailData/ubiquitous_SyncedRules.plist added to work queue
DEBUG: Searching dir ./Library/Mobile Documents.850126691/com~apple~mail/Documents
DEBUG: Skipping ignore file ./Library/Mobile Documents.850126691/com~apple~mail/Documents/.agignore: not readable
DEBUG: Skipping ignore file ./Library/Mobile Documents.850126691/com~apple~mail/Documents/.gitignore: not readable
Bus error: 10
```
Would it be possible to free up more memory as the search goes on? I'm no C programmer, so I wouldn't know how to contribute.

**Comment by ggreer** [comment]
This seems like something more serious than an OOM. Ag uses `mmap()`, so it's bound by virtual memory, not physical. On a 64-bit system (which you're definitely on, since 10.10 only supports 64 bit), there should be no problem with memory usage.

What version of ag are you using? If it's not the latest, can you try the latest release? Also, console.app should have a crash report for ag. You'll probably find it under "User Diagnostic Reports" labeled "ag_datetime_pid_hostname.crash." Here's a screenshot of what it should look like:

![screen shot 2015-01-19 at 21 34 11](https://cloud.githubusercontent.com/assets/200121/5812604/f95f87c6-a022-11e4-9e9f-766ada5f1d41.png)

If you see a crash report, please gist the data. Also, if you can narrow the crash down to one file (searching in deeper and deeper directories until you find the exact one), it would be very helpful if you could upload the file for me to analyze.

**Comment by jawshooah** [comment]
Currently using `ag 0.28.0`.

Here's the [crash report](https://gist.github.com/jawshooah/d33c53fadcb23f0b3dfc). I'll do some digging into the filesystem in a bit.

**Comment by jawshooah** [comment]
Found it. The problem is `~/Library/Mobile\ Documents.850126691/com~apple~mail/Data/MailData/ubiquitous_SyncedRules.plist`.

Here's a [gist](https://gist.github.com/jawshooah/2c5e7500d24ed3f21a76) of the debug output.

It actually seems like this is just a bad file (ellipses mine):
```bash
$ file ubiquitous_SyncedRules.plist
ubiquitous_SyncedRules.plist: ERROR: cannot read `ubiquitous_SyncedRules.plist' (Bad file descriptor)
```

**Comment by jawshooah** [comment]
Actually, I'm getting the same thing for every single file in that `MailData` directory and its lone subdirectory `Signatures`.

**Comment by ggreer** [comment]
Hmm... does disk utility detect any errors? Also, what does `ls -la ubiquitous_SyncedRules.plist` output? Ditto for `xattr -l ubiquitous_SyncedRules.plist`.

**Comment by jawshooah** [comment]
Deleted that directory, and now it works fine. Actually finished searching my home directory (>60G) in under 10 seconds. Damn.

**Comment by ggreer** [comment]
Well... that's one way to solve that problem. A little googling shows others running into bad file descriptor errors when accessing `~/Library/Mobile\ Documents/.../MailData`, but no fixes. Just, "it happens sometimes."

**Comment by jawshooah** [comment]
Yeah, I had a bit of a brain lapse there. Should have saved them somewhere.

Oh well, at least you know it's not your problem :smiley:

**Comment by ggreer** [comment]
Cool. Closing.

**Comment by jawshooah** [comment]
You want me to keep the gists around for future reference, or is it okay to delete them?

**Comment by ggreer** [comment]
Feel free to delete them.
