### ISSUE TITLE
Ag thinks this PDF is not a binary file

### ISSUE THREAD

**Issue by bdesham** [ggreer/the_silver_searcher#637]
I’m using ag 0.29.1, installed on OS X 10.10.2 using Homebrew. It seems that ag thinks that some (but not all!) PDF files are non-binary files, which is of course incorrect. [Here is an example PDF](http://static.esham.io/miscellaneous/2015/ag_binary_file_test.pdf) that triggers the problem. For example:

    $ cd `mktemp -d`    # Make sure there's no .agignore, .git, .gitignore, etc.
    $ curl -O 'http://static.esham.io/miscellaneous/2015/ag_binary_file_test.pdf'
    $ ag -l cat
    ag_binary_file_test.pdf
    $

This PDF was created by a colleague using Microsoft Word 2013 on Windows 7. When I created a PDF using OS X’s built-in print-to-PDF feature, ag correctly identified that file as a binary file.

Any idea what’s going on?

**Comment by okdana** [comment]
`ag` determines whether a file is binary by checking (up to) the first 512 bytes of the file. If it finds a null character (`\0`) or if it finds that more than 10% of the total bytes checked are 'suspicious' (don't look like readable ASCII or UTF-8 chars), it decides that the file is binary. I tested that methodology on your PDF file and it looks like the final count of suspicious bytes is only 2%.

I think this is not the most super accurate method of determining binary-ness, but since `ag`'s primary goal is speed, and it has to perform this determination against every single file it encounters, it probably doesn't have the luxury of being 100% reliable.

On the other hand, i tested the method against 20 random PDFs i happened to have on my hard drive and it only identified 50% of them as binary... which is probably why i'd added `*.pdf` to my `.agignore` once upon a time.

This method will also fail to catch files that aren't technically binary but would probably be considered such for the purposes of your average text search — mostly XML-based formats like SVG and COLLADA.

**Comment by bdesham** [comment]
> On the other hand, i tested the method against 20 random PDFs i happened to have on my hard drive and it only identified 50% of them as binary... which is probably why i'd added *.pdf to my .agignore once upon a time.

Do you think it would be reasonable to immediately tag a file as binary if it starts with `%PDF-`? Or might this be too surprising of a behavior?

> This method will also (obviously) fail to catch files that aren't technically binary but would probably be considered such for the purposes of your average text search — mostly XML-based formats like SVG and COLLADA.

Speaking for myself, I often *do* want to include SVG files in an ag search. I guess this is why the agignore exists :-)

**Comment by okdana** [comment]
Yeah i don't know why i mentioned that anyway, it's irrelevant

I don't think it would be surprising but it is kind of treading on re-implementing `file`, isn't it?

**Comment by ggreer** [comment]
I'm also wary of re-implementing `file`, but I couldn't think of anything better for PDFs. Oh well, this should fix most of it.

**Comment by bdesham** [comment]
:+1:
