### ISSUE TITLE
Integrate ICgrep

### ISSUE THREAD

**Issue by maxnordlund** [ggreer/the_silver_searcher#698]
Instead of [PCRE](http://sljit.sourceforge.net/pcre.html) you could use [ICgrep](http://parabix.costar.sfu.ca/wiki/ICgrep) which uses LLVM for its backend.

I'm not sure if it is any better, but it seams to be use some very nice trickery with SIMD instructions. It also supports Unicode from the get-go, which is always nice.

**Comment by ggreer** [comment]
ICgrep doesn't support backtracking, so it's not nearly as powerful as PCRE.

**Comment by maxnordlund** [comment]
I'd like to know how many people actually rely upon that feature, e.g. `(a+)b+\1`, since you get pathologically bad performance for certain classes of regular expressions.

https://swtch.com/~rsc/regexp/regexp1.html
https://swtch.com/~rsc/regexp/regexp2.html
https://swtch.com/~rsc/regexp/regexp3.html
https://swtch.com/~rsc/regexp/regexp4.html

**Comment by ggreer** [comment]
Unfortunately, ag is popular enough that if even 1% of ag users use PCRE-only regexes, I'll end up with 100+ angry people emailing me.

I knew about other regex libraries when I created ag, and I went with PCRE because it offered the best compromise of features, usability, performance. Like ICgrep, RE2 is not as nearly as powerful as PCRE. Just look at the swaths of NOT SUPPORTED on https://github.com/google/re2/wiki/Syntax. Simple functionality is missing (such as repeat character counts). Also, ag wasn't architected to have easily-swappable regex libraries. It is tightly coupled to PCRE, and looking at the codebase would make this pretty clear. 

I'm sorry if I'm coming across as callous, but your suggestion is comparable to going on the LKML and saying, "Why don't you support FreeBSD jails instead of cgroups?"

**Comment by maxnordlund** [comment]
That is unfortunate for sure, and the first comment was a bit callous. But I do think I understand your sentiment. To use your analogy, I'm not suggesting building an entire jail, when you just want proper process isolation, but I do suggest another form of isolation. As far as I can gather, Re2's C++ interface is modeled after PCRE and it should be possible to switch too.

> Simple functionality is missing (such as repeat character counts).
Isn't that just `a{m,n}` (that is supported by Re2), or am I missing something?

About how powerful PCRE are, yes you can do more with non-regular expressions. But you'll have to accept exponential time complexity, instead of the linear bound that a DFA gives.

**Comment by juanplopes** [comment]
I know the issue is already clused, but the main problem with PCRE is that it displays exponential behavior even in regexes without backtracking. The Russ Cox's material linked by @maxnordlund has a clear example that creates an odd behavior in ag.

```bash
$ printf 'a%.0s' {1..100} > somefile
$ ag '(a?a){100}' somefile
```

The example above does respond quickly, but it seems to do so via some sort of timeout, yielding no results (even having one obvious example). Changing all `100` in the example by `10` yields normal results.
