### ISSUE TITLE
When Ag will be available on cygwin?

### ISSUE THREAD

**Issue by nowox** [ggreer/the_silver_searcher#793]
Usually, the first thing I do when I install Cygwin is to build my silver searcher. I am wondering when it will be available on Cygwin setup.

**Comment by ggreer** [comment]
I don't know. I don't use windows.

**Comment by nowox** [comment]
Neither do I. I use Cygwin which is (almost) POSIX. `ag` builds with no
issues and I use `ag` at least a hundred times a day. I just wanted to know
whether or not it can become part of the standard Cygwin package. I guess
you can contact the mailing list about this https://cygwin.com/ml/cygwin/

**Comment by me-and** [comment]
Hello! I'm in the process of packaging Ag for Cygwin; I'm already the Cygwin package maintainer for Git and fzf. I'll announce it on the Cygwin announcement mailing list (which also gets copied to the main Cygwin list) as soon as it's available.

In general, your best bet for questions about packaging things for Cygwin is to use the Cygwin mailing lists rather than project mailing lists/issue trackers/whatever.

**Comment by nowox** [comment]
This is a great news! fzf is a very nice tool too, I could not live without
it :)

This is clearly off topic, but as you are the Git maintainer, would it be
possible to have Git compiled with PCRE? git grep -P is truly missing.

Next time I'll try the mailling list. Thanks for the advise.

**Comment by lewurm** [comment]
Since this is the first hit on Google, this is the answer: The package is called`the_silver_searcher`. Also see https://cygwin.com/packages/summary/the_silver_searcher.html
